- name: check if /var/source is a git repository
  stat:
    path: /var/source/.git
  register: repo

- name: install git hooks
  sudo: yes
  copy:
    src: "{{ item }}.sh"
    dest: /var/source/.git/hooks/{{ item }}
    owner: "{{ dork_user }}"
    mode: 0755
  with_items:
  - post-commit
  - post-checkout
  when: repo.stat.isdir is defined and repo.stat.isdir
